name: Java CI with Gradle

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build and push
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: |
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          docker build -t chaeyeon1234/next-pick:${GITHUB_SHA::7} .
          docker push chaeyeon1234/next-pick:${GITHUB_SHA::7}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: Deploy to Server
        run: |
          aws ssm send-command \
            --instance-ids i-060f949b84e77e10a \
            --document-name "AWS-RunShellScript" \
            --parameters "commands=[
              'docker pull chaeyeon1234/next-pick:${GITHUB_SHA::7}',
              'docker stop next-pick-container || true',
              'docker rm next-pick-container || true',
              'docker run -d —name next-pick-container -p 8080:8080 chaeyeon1234/next-pick:${GITHUB_SHA::7}'
            ]" \
            —output text